### ISSUE TITLE
Render an off-board issue reference in the console with its title and state icon

### ISSUE THREAD

**Issue by HiromiShikata** [HiromiShikata/npm-cli-github-issue-tower-defence-management#1513]
From: :robot: urgent-taskforce-leader (claude-opus-4-6)

## Goal

An issue or pull request reference rendered in the console item detail shows the referenced item's title and state icon even when that referenced item is not an item on the GitHub Project board.

## Current behaviour

The console renders such a reference as a bare URL with no title and no state icon.

`/api/issuetitle` resolves the state through `getIssueOrPullRequestState`, which reads the GitHub REST API and works for any URL, but it resolves the title through `getIssueByUrl`, which is implemented as `fetchProjectItemByUrl` and returns `null` for any issue that is not an item on the board. `handleIssueTitle` then returns `title: ''`, and `ConsoleReferenceLink` falls back to the plain URL anchor whenever `state.title.trim() === ''`.

## Evidence

Retrieved 2026-08-13T14:55:00Z against the console running on this host, build `1.148.22`.

A board item whose body contains a reference to an issue that is not on the board: https://github.com/HiromiShikata/blog-beauty-aesthetics-review/issues/93 references https://github.com/HiromiShikata/hashigoya-project/issues/656

The rendered anchor in the console item detail for that item:

```html
<a class="console-markdown-reference console-markdown-reference-plain"
   href="https://github.com/HiromiShikata/hashigoya-project/issues/656"
   target="_blank" rel="noopener noreferrer">https://github.com/HiromiShikata/hashigoya-project/issues/656</a>
```

`/api/issuetitle` for that referenced issue, which is not on the board:

```json
{"state":"closed","merged":false,"isPullRequest":false,"title":""}
```

The same endpoint for a referenced issue that is on the board:

```json
{"state":"open","merged":false,"isPullRequest":false,"title":"仕分けが終わったら決算処理依頼"}
```

The referenced issue does have a title. `gh issue view 656 -R HiromiShikata/hashigoya-project --json number,title,state` returns state `CLOSED` and a non-empty title.

## Expected behaviour

- A reference to an issue that is not an item on the GitHub Project board renders as the state icon followed by the referenced issue's title.
- A reference to an issue that is on the board keeps rendering exactly as it does today.
- The rendering of pull request references is unchanged.

## Tasks

- [ ] Add a failing test that resolves the title for a URL whose project item lookup yields nothing and asserts the real title is returned
- [ ] Return the title from `getIssueOrPullRequestState`, which already reads the REST payload that carries it, and consume it in `handleIssueTitle`
- [ ] Update the console end-to-end test harness stub for the changed repository method
- [ ] Confirm in the running console that the reference renders with the state icon and the title

## Executive Summary

The goal of this task is that a reader of the console item detail sees what a referenced issue actually is, by its title and state icon, instead of a bare URL, whenever that referenced issue lives outside the GitHub Project board.
Today the title is resolved only through the project board item lookup, so every reference to an off-board issue renders as a plain URL while its state is already retrieved correctly.
The fix returns the title from the REST call that already retrieves the state, which also removes one API call per referenced pull request.
What remains for this task is the implementation, the tests, and the confirmation in the running console; nothing is awaited from the owner.

**Comment by HiromiShikata** [comment]
From: :robot: urgent-taskforce-leader (claude-opus-4-6)

## Cause established by execution, and the reproducing test committed before the fix

### Cause

The chain is fully traced against the code that is running, build `1.148.22`.

`handleIssueTitle` reads the state through `getIssueOrPullRequestState`, which calls the GitHub REST API and therefore works for any URL, but it read the title through a separate helper that called `getIssueByUrl`. `getIssueByUrl` in `ApiV3CheerioRestIssueRepository` is implemented as:

```ts
getIssueByUrl = async (url: string): Promise<Issue | null> => {
  const projectItem = await this.graphqlProjectItemRepository.fetchProjectItemByUrl(url);
  if (!projectItem) {
    return null;
  }
  return this.convertProjectItemToIssue(projectItem);
};
```

An issue that is not an item on the GitHub Project board has no project item, so this returns `null`, the helper returned `''`, and `ConsoleReferenceLink` takes its plain branch:

```tsx
if (state === null || state.title.trim() === '') {
  return (
    <a className="console-markdown-reference console-markdown-reference-plain" ...>
      {fallbackText}
    </a>
  );
}
```

The state was never the problem — only the title was, and only for URLs outside the board.

### Reproducing test, run before the fix

The tests were committed in `cac12f67`, ahead of the fix, and run against the unfixed code:

```
FAIL backend src/adapter/entry-points/console/consoleReadApi.test.ts
FAIL backend src/adapter/repositories/issue/ApiV3CheerioRestIssueRepository.test.ts
src/adapter/repositories/issue/ApiV3CheerioRestIssueRepository.test.ts:2060:21 - error TS2339: Property 'title' does not exist on type '{ state: string; merged: boolean; isPullRequest: boolean; }'.
src/adapter/repositories/issue/ApiV3CheerioRestIssueRepository.test.ts:2088:21 - error TS2339: Property 'title' does not exist on type '{ state: string; merged: boolean; isPullRequest: boolean; }'.
Test Suites: 2 failed, 2 total
Tests:       0 total
```

The contract carried no title at all, so the assertion could not even be expressed against the unfixed code. The behavioural reproduction is the live one already recorded in the issue body: `/api/issuetitle` returned `title: ""` for an off-board issue that does have a title.

### Change

`getIssueOrPullRequestState` now returns the title from the REST payload it already fetches, for both issues and pull requests, and `handleIssueTitle` returns that state directly. The separate title lookup is deleted, so a referenced pull request now costs one REST call instead of two, and no reference depends on board membership.

Three existing expectations changed because the behaviour they asserted is the behaviour this task removes: the two that asserted the title came from the project item lookup and the pull request summary, and the one named `falls back to an empty title when the title source returns nothing`, which encoded the defect itself. The stubs in the console end-to-end harness and in the two in-tmux-by-human reconciler tests were extended with the new field.

### Test result after the fix

```
Test Suites: 6 passed, 6 total
Tests:       167 passed, 167 total
```

covering `consoleReadApi`, `ApiV3CheerioRestIssueRepository`, `src/domain/usecases/intmux` and `inTmuxByHumanSessionReconciler`.

## Executive Summary

The goal of this task is that a reader of the console item detail sees a referenced issue by its title and state icon rather than as a bare URL, including when that issue is not an item on the GitHub Project board.
The cause is that the title was resolved through the project board item lookup while the state was resolved through the REST API, so every off-board reference returned an empty title and fell back to plain rendering.
The fix returns the title from the REST call that already retrieves the state, which also removes one REST call per referenced pull request.
What remains for this task is the pull request, the CI run, and the confirmation in the running console after the release reaches this host; nothing is awaited from the owner.

**Comment by HiromiShikata** [comment]
From: :robot: urgent-taskforce-leader (claude-opus-4-6)

## Pull request opened, CI running

The change is on the branch `i1513-off-board-reference-title` and the pull request that carries it is the following one.

https://github.com/HiromiShikata/npm-cli-github-issue-tower-defence-management/pull/1514

Its "Depended Issue URL separated by comma" field is set to this issue, and the check runs are being polled.

## Changed contract

`getIssueOrPullRequestState` gains `title` in its return type:

```ts
getIssueOrPullRequestState: (url: string) => Promise<{
  state: string;
  merged: boolean;
  isPullRequest: boolean;
  title: string;
}>;
```

Feasibility is confirmed rather than assumed: the GitHub REST payloads this method already fetches — `GET /repos/{owner}/{repo}/issues/{number}` and `GET /repos/{owner}/{repo}/pulls/{number}` — both carry `title`, which the live response recorded earlier in this issue demonstrates. No additional request is introduced, and one request per referenced item is removed.

The one other production consumer, `InTmuxByHumanSessionReconcileUseCase`, reads only `state` and is unaffected by the added field. `ApiV3CheerioRestIssueRepository` is the only implementation of `IssueRepository` in the repository.

```mermaid
sequenceDiagram
    participant Reader as Console reader
    participant Link as ConsoleReferenceLink
    participant Hook as useConsoleReferenceLink
    participant Api as GET /api/issuetitle
    participant Repo as ApiV3CheerioRestIssueRepository
    participant GitHub as GitHub REST API

    Reader->>Link: opens an item whose body holds an issue URL
    Link->>Hook: request the referenced item state
    Hook->>Api: url of the referenced issue
    Api->>Repo: getIssueOrPullRequestState(url)
    Repo->>GitHub: GET /repos/{owner}/{repo}/issues/{number}
    GitHub-->>Repo: state and title
    Repo-->>Api: state, merged, isPullRequest, title
    Api-->>Hook: response, then cached for 300 seconds
    Hook-->>Link: state carrying a non-empty title
    Link-->>Reader: state icon followed by the issue title
```

## Executive Summary

The goal of this task is that a reader of the console item detail sees a referenced issue by its title and state icon rather than as a bare URL, including when that issue is not an item on the GitHub Project board.
The fix is implemented, its tests pass locally, and it is now on the pull request linked above with its check runs in progress.
The contract change adds a field that the REST payload already carries, so it introduces no new request and removes one request per referenced item.
What remains for this task is the CI result, the release reaching the scheduling host, and the confirmation in the running console that the reference renders with its title and state icon; nothing is awaited from the owner.

**Comment by HiromiShikata** [comment]
From: :robot: urgent-taskforce-leader (claude-opus-4-6)

## PR URL

https://github.com/HiromiShikata/npm-cli-github-issue-tower-defence-management/pull/1514

## Root cause of problem and why this changes work

The console item detail resolved the state of a referenced issue or pull request through `getIssueOrPullRequestState`, which reads the GitHub REST API and works for any URL, but resolved its title through `getIssueByUrl`, which is implemented as `fetchProjectItemByUrl`. An issue that is not an item on the GitHub Project board has no project item, so the title came back empty and `ConsoleReferenceLink` took its plain branch, which renders the bare URL.

Returning the title from the REST payload that the state call already fetches removes the dependency on board membership entirely, for issues and for pull requests alike, and removes one request per referenced item.

## Verification in the running console

A console server was built from this branch and started on port 9981 against the same generated data and the same project as the one the scheduling host runs, so the two differ only in the code under test. The same board item was opened in both.

The item is https://github.com/HiromiShikata/blog-beauty-aesthetics-review/issues/93 and the reference in its body is to https://github.com/HiromiShikata/hashigoya-project/issues/656 , which is not an item on the board.

`/api/issuetitle` for that reference, from the published build 1.148.22 that the host is running:

```json
{"state":"closed","merged":false,"isPullRequest":false,"title":""}
```

and from the branch build:

```json
{"state":"closed","merged":false,"isPullRequest":false,"title":"#106と共に対応/背中のほくろの様子が変かもしれないので病院調査と予約をお願いします🙇"}
```

The rendered anchor in the item detail, from the published build:

```html
<a class="console-markdown-reference console-markdown-reference-plain"
   href="https://github.com/HiromiShikata/hashigoya-project/issues/656">https://github.com/HiromiShikata/hashigoya-project/issues/656</a>
```

and from the branch build, where the `-plain` class is gone and the state icon and the title are present:

```html
<a class="console-markdown-reference" href="https://github.com/HiromiShikata/hashigoya-project/issues/656">
  <svg class="console-item-icon" viewBox="0 0 16 16" width="12" height="12" fill="#a371f7" role="img" aria-label="issueClosed">…</svg>
  <span class="console-markdown-reference-title">#106と共に対応/背中のほくろの様子が変かもしれないので病院調査と予約をお願いします🙇</span>
</a>
```

The purple `issueClosed` icon matches the referenced issue's real state, which `gh issue view 656 -R HiromiShikata/hashigoya-project` reports as CLOSED.

Screen captures of both states were taken under identical conditions but could not be attached: the sanctioned attachment command reports `Source: none` and no `user_session` cookie in any of its sources. That blocker is recorded at https://github.com/HiromiShikata/secretary/issues/3274 . The DOM above is the retrieved artifact itself, not a substitute for it.

## Reproducing test failing before the fix

The reproducing tests were committed in `cac12f67`, ahead of the fix in `03067db2`. Their first form could only fail as a TypeScript error, because the contract carried no `title` at all. They were rewritten to assert the returned object as a whole, which executes the function and fails on the value. Run with the production files restored to `origin/main`:

```
● ApiV3CheerioRestIssueRepository › getIssueOrPullRequestState › should return the issue title carried by the same REST payload

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 0

      Object {
        "isPullRequest": false,
        "merged": false,
        "state": "closed",
    -   "title": "Issue title from REST",
      }
```

With the fix in place the same suites report `Test Suites: 2 passed`, `Tests: 124 passed`.

## Answers for all questions and comments

### Does tightening the response guard to require `title` widen the blast radius?

The other production caller of `getIssueOrPullRequestState` is `InTmuxByHumanSessionReconcileUseCase`, which reads only `state`. The GitHub REST issue and pull request payloads always carry `title`. A payload without it now throws a named error rather than silently yielding an empty title, which is the behaviour the policy on error suppression requires, and `6ecbfc53` adds a test asserting exactly that rejection.

### Why were three existing expectations changed?

They asserted the behaviour this task removes: two asserted the title came from the project item lookup and from the pull request summary, and one named `falls back to an empty title when the title source returns nothing` encoded the defect itself. No assertion was weakened to make the implementation pass.

## セルフチェック

- 🟢 このソースコードが本番環境に反映されることで本番環境を破壊する可能性がある
- 🟢 リポジトリの開発ドキュメントに従っていない
- 🟢 開発ポリシーに従っていない
- 🟢 本番/ソースコードを変更したのに、変更後の挙動をカバーするテストを追加・更新していない

## Review Readiness Self-Check

```json
{"reviewReady":true,"rejections":[]}
```

## Six-perspective rubric

- Architecture / Design: L5. The added field sits on the domain adapter interface, its single implementation, and the console entry point that consumes it; a redundant indirection is deleted rather than patched.
- Test design and test pyramid: L4. Unit tests at the repository and read-API levels, plus a rejection test for the tightened guard; the reproduction executes the function and fails on the value.
- Scenario coverage: L4. Off-board issue, on-board issue, pull request, cache miss, cache TTL, permanently cached merged result, and a payload without a title.
- Code quality and readability: L5. No dead mock setup remains; the off-board test now asserts that the project item lookup is not called.
- Spec conformance: L5. All four task items in the issue body are done, including the confirmation in a running console.
- Deploy / environment impact and security: L4. A push to `main` publishes to npm and every host installs from there; this change removes requests rather than adding them, and its only behavioural change on the shared path is a loud failure where a silent empty value used to pass.

## エグゼクティブサマリ

タスクのゴール: TDPM コンソールの詳細画面で、GitHub Project のボードに載っていない issue への参照が、素の URL ではなく状態アイコンとタイトルで表示されるようにすることです。
実施内容: 状態を取得する REST 呼び出しがすでに受け取っているタイトルを返すように契約を変え、ボード項目を引く別経路を削除したうえで、この分岐を実行するテストを修正前コードで失敗させてから修正しました。
考慮事項: main へのマージは npm 公開を伴い全ホストに配布されますが、本変更は参照 1 件あたりのリクエストを 1 つ減らす方向にのみ働き、タイトルを持たない応答は無言の空文字ではなく明示的な例外になります。
残作業: このプルリクエストのマージと、公開されたビルドが本ホストに入った後の再確認だけです。オーナーの判断や承認を要する事項はありません。

**Comment by HiromiShikata** [comment]
From: :robot: urgent-taskforce-leader (claude-opus-4-6)

## Merged

https://github.com/HiromiShikata/npm-cli-github-issue-tower-defence-management/pull/1514

Merged at 2026-08-13T15:52:44Z into `main`, merge commit produced by the auto-merge that this repository's pull request workflow enables on creation. I posted my own approving review immediately before that, at 2026-08-13T15:51Z, after the pre-handover review returned PASS.

State immediately before the approval, retrieved at 2026-08-13T15:50:00Z: head `86442a9427d0c50a4bfe1227db6a4e0248807a54`, 15 checks total, none failing, none pending, `mergeable: MERGEABLE`, `isDraft: false`, and `reviewDecision: REVIEW_REQUIRED` as the only remaining block.

## Authorization for the merge

The owner instructed in the live session at 2026-08-13T07:37:05Z, verbatim:

> 何度も言いましたが、tdpm の修正はあなたで評価しの味してくださいと言ったはずです

The owner dictates by voice, and 「評価しの味して」 is the transcription of 「評価しマージして」. The instruction grants me the evaluation and the merge of fixes to this repository. This pull request is a fix to this repository, so it falls inside the stated scope. No branch protection rule and no required check was bypassed: every required check was already passing and the merge went through the ordinary approval path.

## What ships

A merge to `main` triggers `.github/workflows/publish.yml`, which publishes the package to npm, and every host installs from npm. The change is therefore now on its way to all hosts.

## Remaining work on this issue

I am watching the publish workflow and the npm registry, and after the new version is installed on this host I will re-open the same board item on the running console and confirm that the off-board reference renders with its icon and title on the published build, then record that output here. That is the only item left, and it needs nothing from the owner.

## Executive Summary

The goal of this task is to make the TDPM console show the icon and the title for a referenced issue or pull request that is not an item on the GitHub Project board, instead of rendering it as a bare URL.

I established the cause end to end, committed a test that fails at runtime against the unfixed code, fixed it by returning the title from the REST payload that the state call already retrieves, and verified the corrected rendering in a running console built from the branch.

The pull request is merged and the npm publish workflow is running, which distributes the change to every host that installs this package.

What remains is my own confirmation of the corrected rendering on the published build once it is installed on this host; nothing on this issue requires a judgment or an approval from the owner.

**Comment by HiromiShikata** [comment]
From: :robot: urgent-taskforce-leader (claude-opus-4-6)

## Verified on the published build running on this host

Release `1.148.23` was published by `.github/workflows/publish.yml` from `main` after the merge, and this host now runs it.

Installed version on this host:

```
$ readlink -f /home/hiromi/.local/share/tdpm/current
.../versions/1.148.23
```

The installed build carries the fix. `handleIssueTitle` in the shipped bundle no longer performs the project-board lookup, and the removed helper is gone from the artifact:

```
$ grep -n "handleIssueTitle" -A 11 .../bin/adapter/entry-points/console/consoleReadApi.js
138:const handleIssueTitle = async (issueRepository, cache, url) => {
139-    if (!url) {
140-        return badRequest('url query parameter is required');
141-    }
142-    const cached = cache.get(url);
143-    if (cached !== null) {
144-        return ok(cached);
145-    }
146-    const state = await issueRepository.getIssueOrPullRequestState(url);
147-    cache.set(url, state);
148-    return ok(state);
149-};

$ grep -c "resolveIssueOrPullRequestTitle" .../bin/adapter/entry-points/console/consoleReadApi.js
0
```

The console process serving port 9980 on this host was restarted at 2026-08-13T15:55:11Z and resolves `current`, so it is running `1.148.23`.

The read API on that running console, queried at 2026-08-13T15:55:57Z for the same off-board issue used in the before-and-after comparison:

```
$ curl -H "x-pv-token: ***" "http://127.0.0.1:9980/api/issuetitle?url=https%3A%2F%2Fgithub.com%2FHiromiShikata%2Fhashigoya-project%2Fissues%2F656"
{"state":"closed","merged":false,"isPullRequest":false,"title":"#106と共に対応/背中のほくろの様子が変かもしれないので病院調査と予約をお願いします🙇"}
```

Before the fix, the same request against the same running console returned `"title":""`.

I then reached the item through the user interface rather than by a direct URL: I opened `http://127.0.0.1:9980/`, followed the `umino` project, opened the `Todo by human` tab, and clicked the card titled `背中のほくろ取り`, which navigated to `http://127.0.0.1:9980/projects/umino/todo-by-human#item/PVTI_lAHOAGJHa84AFWnrzgIxX48`. The rendered anchor in that detail view is now:

```html
<a class="console-markdown-reference" href="https://github.com/HiromiShikata/hashigoya-project/issues/656" target="_blank" rel="noopener noreferrer"><svg class="console-item-icon" viewBox="0 0 16 16" width="12" height="12" fill="#a371f7" role="img" aria-label="issueClosed"> … </svg><span class="console-markdown-reference-title">#106と共に対応/背中のほくろの様子が変かもしれないので病院調査と予約をお願いします🙇</span></a>
```

Before the fix, the same anchor on the same item carried `class="console-markdown-reference-plain"`, had no icon, and its text was the bare URL. A query for `a.console-markdown-reference-plain` in the current detail view returns zero elements.

The screen capture could not be attached because the attachment upload command is failing on this host for a reason unrelated to this repository, which is recorded on the internal operations repository; the retrieved DOM above is the primary artifact rather than a substitute for it.

## Executive Summary

The goal of this task is to make the TDPM console show the icon and the title for a referenced issue or pull request that is not an item on the GitHub Project board, instead of rendering it as a bare URL.

The fix is merged, published as release `1.148.23`, installed on this host, and I confirmed the corrected rendering by navigating the running console through its own user interface to the same item used for the before-and-after comparison.

The change also removes one API call per rendered reference, because the title now comes from the payload the state request already retrieves.

Nothing remains on this task, and it needs no judgment or approval from the owner.
