### ISSUE TITLE
The default branch does not compile, so publish is skipped

### ISSUE THREAD

**Issue by HiromiShikata** [HiromiShikata/npm-cli-github-issue-tower-defence-management#1523]
From: :robot: urgent-taskforce-leader (claude-opus-4-6)

## What is broken

The default branch does not compile, so the `test` job fails and the `publish` job is skipped. No release reaches npm while this lasts.

Failing run on `main` at commit `cb9087ef`: https://github.com/HiromiShikata/npm-cli-github-issue-tower-defence-management/actions/runs/31739607709

The compiler output is:

```
src/domain/usecases/intmux/UnansweredOwnerCallSessionKeyContract.test.ts:94:45 - error TS2322
Property 'title' is missing in type '{ state: string; merged: false; isPullRequest: false; }'
but required in type '{ state: string; merged: boolean; isPullRequest: boolean; title: string; }'
```

3096 tests passed and none failed; the suite failed to run because it does not type check.

## Why both pull requests were green

`UnansweredOwnerCallSessionKeyContract.test.ts` supplies a fake `getIssueOrPullRequestState` and was added by https://github.com/HiromiShikata/npm-cli-github-issue-tower-defence-management/pull/1512

`title` was added to `getIssueOrPullRequestState` in `src/domain/usecases/adapter-interfaces/IssueRepository.ts` by https://github.com/HiromiShikata/npm-cli-github-issue-tower-defence-management/pull/1514

The merge base of the 1512 branch is `1076ff44`, and the interface at that commit and on the 1512 branch tip carries no `title`. Pull request 1514 reached `main` after that merge base. Each branch compiled on its own and neither branch's CI could observe the other's change, so the break appears only in their combination on `main`.

## Observable outcome this issue asks for

`main` compiles and the `test` job passes, so the `publish` job runs again, and the contract test keeps asserting the same thing it asserts today.

## エグゼクティブサマリ

このissueのゴールは、default branch のコンパイルを回復させ、`test` の失敗により停止している `publish` を再び動作させることです。
`UnansweredOwnerCallSessionKeyContract.test.ts` の偽実装が `getIssueOrPullRequestState` の必須プロパティ `title` を返しておらず、型検査に失敗してスイートが実行できていません。
`title` を追加した pull request と当該テストを追加した pull request は互いの変更を含まない状態でそれぞれ緑になっており、`main` 上での組み合わせで初めて破綻しました。
このissueに残っているのは修正の実装であり、オーナーのご判断をお待ちしている事項はありません。

**Comment by HiromiShikata** [comment]
From: :robot: urgent-taskforce-leader (claude-opus-4-6)

## Released and verified on a running host

The default branch was repaired by https://github.com/HiromiShikata/npm-cli-github-issue-tower-defence-management/pull/1524 , merged at 2026-08-13T20:40:18Z as `fce465d0`. On that commit `test` completed successfully, `publish` then ran, version 1.151.0 reached npm, and the host installed it. Both npm and the host report 1.151.0.

This supersedes my earlier comment on this pull request, which reported that no release had been published.

### The feature is live, measured rather than assumed

Version 5 documents are now written by the running daemon. Checking the deployed documents themselves:

```
sessions: 3
sessionsWithCalls: 3
totalCalls: 3
entryKeys: body,calledAt
isoUtcMillisFormat: true
distinctTimes: 3
bodyNonEmpty: true
bodyCharLengths: [627, 599, 352]
```

Every call entry carries exactly `calledAt` and `body`. Every `calledAt` matches ISO 8601 UTC with milliseconds, and the three times are distinct, which is what makes the timestamp usable as the identity of a call. Every body is real, non-empty call text. The bodies are not reproduced here because this repository is public.

Version 4 is unchanged: no session in the version 4 document carries `unansweredCalls`.

The delivery path was exercised over HTTP against the running console rather than only on disk. `/in-tmux-by-human/{pjcode}.v5.json` returns HTTP 200 with the console access token and serves `version` 5, and returns HTTP 401 without it.

This satisfies the last completion condition of the task issue, that a version 5 document fetched from a running host contains the real bodies and times of that host's unanswered calls.

### One correction to my own checking

An initial aggregate query of mine reported a null value and I nearly recorded it as a defect. The cause was my own query reading `index.v5.json`, whose shape is `{version, projects}` and which has no `groups` key, so iterating `groups` produced null. Re-run against the project documents only, no null exists: `groups` is an array in every document and every `unansweredCalls` is an array. Separately, a timestamp check of mine reported failure because the tool I used rejects fractional seconds; the timestamps are well formed. Neither was a defect in the shipped code.

## エグゼクティブサマリ

タスクのゴール: オーナーが端末を離れて戻ったときに、各セッションが何について呼び出したのかを本文と時刻つきで読めるようにすることです。
実施内容: default branch を修復して 1.151.0 を公開し、稼働中のホスト上で version 5 文書が実際に生成され、3件の呼び出しが本文と一意な ISO 8601 UTC 時刻を伴って配信されていることを実測しました。
考慮事項: version 4 文書は変更されておらず、version 5 の配信経路はコンソールアクセストークンなしでは HTTP 401 となることを実機で確認しています。
残作業: 本 pull request に関して残っている作業はありません。

**Comment by HiromiShikata** [comment]
From: :robot: urgent-taskforce-leader (claude-opus-4-6)

## Correction to the wording of this issue's body

The body of this issue says "3096 tests passed and none failed; the suite failed to run because it does not type check". Read together those two statements contradict each other, because a suite that did not run cannot have contributed passing tests. The body is not edited, so the accurate wording is recorded here.

What actually happened is that jest ran, and 3096 tests across the other suites passed with none failing. Exactly one suite could not run: `UnansweredOwnerCallSessionKeyContract.test.ts`, which jest reported as "Test suite failed to run" because it did not type check. The job failed on that single suite rather than on any assertion.

This wording does not change the cause, the fix, or anything that was verified. It is corrected so a later reader is not left with a contradiction in the record.

## エグゼクティブサマリ

このissueのゴールは、default branch のコンパイルを回復させ、`test` の失敗により停止していた `publish` を再び動作させることでした。
本コメントは、issue 本文にあった「3096件のテストが成功した」と「スイートが実行できなかった」という相互に矛盾する記述を、正確な表現に訂正するものです。
実際には jest は動作しており、他のスイートの3096件は成功し、型検査に失敗した1つのスイートのみが実行できませんでした。
訂正は表現のみであり、原因、修正内容、検証済みの事実は変わりません。
このissueに残っている作業はありません。
